OLED_ENABLE = yes
WPM_ENABLE = yes  # Enable word per minute counter
DYNAMIC_TAPPING_TERM_ENABLE = yes
DYNAMIC_TAPPING_TERM_INCREMENT = 50

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_ATTENUATION = EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
CIRQUE_PINNACLE_CURVED_OVERLAY = yes

SPLIT_KEYBOARD = yes

ENCODER_ENABLE = no       # Enables the use of one or more encoders
#BACKLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow

#CIRQUE_PINNACLE_DIAMETER_MM = 35
#CIRQUE_PINNACLE_ATTENUATION = EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X # EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X least sensitive, EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X most sensitive

#CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_ABSOLUTE_MODE
#CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_RELATIVE_MODE

# Relative mode settings
#CIRQUE_PINNACLE_TAP_ENABLE = yes
#CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE = yes
#POINTING_DEVICE_GESTURES_SCROLL_ENABLE = yes

# Absolute mode settings
#CIRQUE_PINNACLE_TAP_ENABLE = yes
#CIRQUE_PINNACLE_TAPPING_TERM = 200
#CIRQUE_PINNACLE_TOUCH_DEBOUNCE = 200
#POINTING_DEVICE_GESTURES_SCROLL_ENABLE = yes
#POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE = yes


